services:
  postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES="${PG_DB_DEV_NIL}"
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./.snippets/postgres/init-databases:/docker-entrypoint-initdb.d
      - ./.docker/postgres:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - ./.docker/redis:/data

  mariadb:
    image: mariadb:11.4
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_MULTIPLE_DATABASES=${MARIADB_MULTIPLE_DATABASES}
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./.snippets/mariadb/init-databases:/docker-entrypoint-initdb.d
      - ./.snippets/mariadb/conf.d:/etc/mysql/conf.d
      - ./.docker/mariadb:/var/lib/mysql

  # legacy mysql - impl my prod
  percona:
    image: percona:5.7.43
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${PERCONA_DATABASE}
      - MYSQL_USER=${PERCONA_USER}
      - MYSQL_PASSWORD=${PERCONA_PASSWORD}
    ports:
      - ${PERCONA_PORT}:3306
    volumes:
      - ./.docker/percona:/var/lib/mysql
